name: Auto Update Products

on:
  schedule:
    - cron: '18 2 * * *'  # 每天 10:18 (台灣) 左右（runner 使用 UTC），可自行調整
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Run updater
        run: node scripts/update_products.mjs

      - name: Commit & Push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'data/products.json'
          message: 'chore: auto-update products.json'
          default_author: github_actions
